apiVersion: batch/v1
kind: CronJob
metadata:
  name: caas-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: caas-ops
          containers:
          - name: caas-hc-pod
            image: quay.io/openshift/origin-cli
            command: ["/bin/sh", "-c", "cat /app/check_status.sh | /bin/sh"]
            volumeMounts: 
            - mountPath: /app
              name: hcvolume
          volumes: 
          - name: hcvolume 
            configMap:
              name: caas-configmap
              items:
              - key: check_status.sh
                path: check_status.sh
          restartPolicy: OnFailure
---

# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: myclusterrole
# rules:
#   apiGroups: [""]
#   resources: ["pods", "nodes"]
#   verbs: ["get", "list"]
# ---

# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: myclusterrolebinding
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: myclusterrole
# subjects:
# - kind: ServiceAccount
#   name: myserviceaccount
#   namespace: default
# ---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: caas-sa
spec:
  serviceAccountName: caas-ops

apiVersion: v1
kind: ConfigMap
metadata:
  name: caas-configmap
data:
  check_status.sh: |
    #!/bin/sh

    echo "################# oc get nodes  ####################################"
    oc get node

    echo "################# oc get custom operator ###########################" 
    oc get co 

    echo "################# oc get evicted POD ###############################" 
    oc get pod -A | egrep -v 'Running|Completed'



