apiVersion: batch/v1
kind: CronJob
metadata:
  name: mycronjobvol
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ocsa
          containers:
          - name: myapp
            image: quay.io/openshift/origin-cli
            command: ["/bin/sh", "-c", "cat /check_status.sh | /bin/sh"]
            volumeMounts: 
            - mountPath: /check_status.sh
              name: myvolume
          volumes: 
          - name: myvolume 
            hostPath:
              path: /var/home/core/logvol/check_status.sh
              type: File
          restartPolicy: OnFailure
---

# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: myclusterrole
# rules:
#   apiGroups: [""]
#   resources: ["pods", "nodes"]
#   verbs: ["get", "list"]
# ---

# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: myclusterrolebinding
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: myclusterrole
# subjects:
# - kind: ServiceAccount
#   name: myserviceaccount
#   namespace: default
# ---

#apiVersion: v1
#kind: ServiceAccount
#metadata:
 # name: myserviceaccountvol
#spec:
 # serviceAccountName: myserviceaccountvol
